name: Build on Ubuntu
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setting envs
        env:
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS: ${{ secrets.AWS_SECRET_ACCESS }}
          AWS_CLIENT_SECRET: ${{ secrets.AWS_CLIENT_SECRET }}
          AWS_PROFILE: ${{ secrets.AWS_PROFILE }}
          AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
          AWS_SECURITY_TOKEN: ${{ secrets.AWS_SECURITY_TOKEN }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          echo $AZURE_CLIENT_SECRET      
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt-get update
          sudo mv "${GITHUB_WORKSPACE}/binaries/dkp" /usr/local/bin/dkp
          sudo mv "${GITHUB_WORKSPACE}/binaries/kommander" /usr/local/bin/kommander
          sudo chmod +x /usr/local/bin/dkp
          sudo chmod +x /usr/local/bin/kommander
      - name: Make script executable
        run: |
          chmod +x "${GITHUB_WORKSPACE}/deploy"
      - name: Run install script
        run: |
          "${GITHUB_WORKSPACE}/deploy"
