name: Build on Ubuntu
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setting envs
        env:
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        run: |
          echo envs set      
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt-get update
          sudo mv "${GITHUB_WORKSPACE}/binaries/dkp" /usr/local/bin/dkp
          sudo mv "${GITHUB_WORKSPACE}/binaries/kommander" /usr/local/bin/kommander
          sudo chmod +x /usr/local/bin/dkp
          sudo chmod +x /usr/local/bin/kommander
      - name: Make script executable
        run: |
          chmod +x "${GITHUB_WORKSPACE}/deploy"
      - name: Run install script
        run: |
          source "${GITHUB_WORKSPACE}/config.d/*"
          "${GITHUB_WORKSPACE}/deploy"
